-- MySQL Script generated by MySQL Workbench
-- Sat Aug 15 17:21:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usco_db_model
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usco_db_model
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usco_db_model` ;
USE `usco_db_model` ;

-- -----------------------------------------------------
-- Table `usco_db_model`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usco_db_model`.`Estudiante` (
  `idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `numID` VARCHAR(20) NOT NULL,
  `programa` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usco_db_model`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usco_db_model`.`Materia` (
  `idMateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `creditos` INT NOT NULL,
  `numSemestre` INT NOT NULL,
  `definitiva` FLOAT NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usco_db_model`.`Semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usco_db_model`.`Semestre` (
  `idSemestre` INT NOT NULL AUTO_INCREMENT,
  `numSemestre` INT NOT NULL,
  `ponderado` FLOAT NOT NULL,
  `Estudiante_idEstudiante` INT NOT NULL,
  PRIMARY KEY (`idSemestre`, `Estudiante_idEstudiante`),
  INDEX `fk_Semestre_Estudiante1_idx` (`Estudiante_idEstudiante` ASC) VISIBLE,
  CONSTRAINT `fk_Semestre_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `usco_db_model`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `usco_db_model`.`estudiante` (`idEstudiante`, `codigo`, `nombre`, `apellido`, `numID`, `programa`) 
VALUES ('1', '20162152116', 'JUAN ANDRES', 'BORRERO IPUS', '1075318934', 'INGENIERIA DE SOFTWARE');



INSERT INTO `usco_db_model`.`materia` (`idMateria`, `nombre`, `creditos`, `numSemestre`, `definitiva`) 
VALUES 
('1', '	COMPUTACION FISICA (INGLES)', '4', '1', '5.0'),
('2', 'COMUNICACION LINGUISTICA', '2', '1', '3.5'),
('3', 'FUNDAMENTOS DE PROGRAMACION', '3', '1', '4.0'),
('4', 'PROGRAMACION ORIENTADA A OBJETOS', '3', '2', '5.0'),
('5', 'PROYECTO INTEGRADOR I (COMPUTACION FISICA)', '3', '2', '4.2'),
('6', 'ARQUITECTURA DE HARDWARE', '3', '2', '3.4'),
('7', 'PROGRAMACION WEB', '3', '3', '4.9'),
('8', 'BASES DE DATOS', '3', '3', '4.4'),
('9', 'INGENIERIA DE SOFTWARE', '3', '3', '4.1'),
('10', 'PROGRAMACION DISPOSITIVOS MOVILES', '3', '4', '5.0'),
('11', 'PROYECTO INTEGRADOR II', '3', '4', '4.5'),
('12', 'ANALISIS Y DISEÑO ORIENTADO A OBJETOS', '3', '4', '4.4');


INSERT INTO `usco_db_model`.`semestre` (`idSemestre`, `numSemestre`, `ponderado`, `Estudiante_idEstudiante`) VALUES ('1', '1', '4.3', '1');
INSERT INTO `usco_db_model`.`semestre` (`idSemestre`, `numSemestre`, `ponderado`, `Estudiante_idEstudiante`) VALUES ('2', '2', '4.2', '1');
INSERT INTO `usco_db_model`.`semestre` (`idSemestre`, `numSemestre`, `ponderado`, `Estudiante_idEstudiante`) VALUES ('3', '3', '4.5', '1');
INSERT INTO `usco_db_model`.`semestre` (`idSemestre`, `numSemestre`, `ponderado`, `Estudiante_idEstudiante`) VALUES ('4', '4', '4.6', '1');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
